export const hotels_data = [
  { name: "Grand Plaza Hotel", city: "New York", starRating: 5, address: "123 Broadway, Manhattan, NY 10001", description: "Luxury hotel in the heart of Manhattan with stunning city views and premium amenities.", manager: "Sarah Johnson", amenities: ["Spa","Pool","Fine Dining","Concierge","Business Center"] },
  { name: "Ocean View Resort", city: "Miami", starRating: 4, address: "456 Ocean Drive, Miami Beach, FL 33139", description: "Beachfront resort with private beach access, spa facilities, and tropical gardens.", manager: "Carlos Rodriguez", amenities: ["Private Beach","Spa","Pool","Water Sports","Beach Bar"] },
  { name: "Mountain Retreat Lodge", city: "Denver", starRating: 4, address: "789 Mountain Road, Denver, CO 80202", description: "Cozy lodge nestled in the mountains with fireplace rooms and hiking trails.", manager: "Emily Chen", amenities: ["Fireplace","Hiking","Spa","Restaurant","Ski Storage"] },
  { name: "Metropolitan Suites", city: "Chicago", starRating: 4, address: "321 Michigan Avenue, Chicago, IL 60601", description: "Modern suites in downtown Chicago with lake views and executive services.", manager: "Michael Brown", amenities: ["Lake View","Business Center","Fitness","Concierge","Valet Parking"] },
  { name: "Sunset Beach Hotel", city: "Los Angeles", starRating: 3, address: "654 Sunset Boulevard, LA, CA 90028", description: "Boutique hotel near Hollywood with pool and celebrity sightings.", manager: "Jessica Williams", amenities: ["Pool","Rooftop Bar","Fitness","Entertainment","Tour Desk"] },
  { name: "Historic Grand Hotel", city: "Boston", starRating: 5, address: "987 Beacon Street, Boston, MA 02108", description: "Historic luxury hotel with traditional elegance and modern comforts.", manager: "Robert Davis", amenities: ["Historic","Fine Dining","Spa","Library","Wine Cellar"] },
  { name: "Desert Oasis Resort", city: "Phoenix", starRating: 4, address: "258 Palm Canyon Drive, Phoenix, AZ 85001", description: "Luxury desert resort with golf course, spa, and mountain views.", manager: "Maria Garcia", amenities: ["Golf Course","Spa","Pool","Tennis","Fine Dining"] },
  { name: "Harbor Lights Inn", city: "San Francisco", starRating: 3, address: "147 Fisherman's Wharf, SF, CA 94133", description: "Charming inn near the bay with cable car access and seafood restaurant.", manager: "David Wilson", amenities: ["Bay View","Seafood Restaurant","Tour Desk","Free WiFi","Bike Rental"] },
  { name: "Executive Business Hotel", city: "Seattle", starRating: 4, address: "369 Tech Center Drive, Seattle, WA 98101", description: "Modern hotel for business travelers with meeting facilities and high-speed internet.", manager: "Jennifer Lee", amenities: ["Business Center","Meeting Rooms","Fitness","Restaurant","Airport Shuttle"] },
  { name: "Garden Paradise Resort", city: "Orlando", starRating: 5, address: "753 Theme Park Road, Orlando, FL 32830", description: "Family-friendly resort near theme parks with water park and kids activities.", manager: "Thomas Miller", amenities: ["Water Park","Kids Club","Pool","Restaurants","Shuttle Service"] },
  { name: "Urban Loft Hotel", city: "Austin", starRating: 3, address: "852 Music Lane, Austin, TX 78701", description: "Trendy hotel in downtown Austin with live music and rooftop bar.", manager: "Amanda Taylor", amenities: ["Live Music","Rooftop Bar","Fitness","Art Gallery","Bike Rental"] },
  { name: "Lakeside Retreat", city: "Minneapolis", starRating: 4, address: "159 Lake Street, Minneapolis, MN 55401", description: "Serene hotel on the lake with water activities and nature trails.", manager: "Christopher Moore", amenities: ["Lake Access","Boating","Fishing","Spa","Restaurant"] },
  { name: "Capital View Hotel", city: "Washington DC", starRating: 4, address: "456 Constitution Avenue, DC 20001", description: "Elegant hotel near national monuments with panoramic city views.", manager: "Elizabeth White", amenities: ["City View","Museum Access","Fitness","Business Center","Fine Dining"] },
  { name: "Boutique Arts Hotel", city: "Portland", starRating: 3, address: "963 Artisan Way, Portland, OR 97205", description: "Art-themed boutique hotel with local artwork and creative atmosphere.", manager: "Daniel Clark", amenities: ["Art Gallery","Local Art","Cafe","Bike Rental","Tour Desk"] },
  { name: "Luxury Sky Hotel", city: "Las Vegas", starRating: 5, address: "147 Casino Strip, Las Vegas, NV 89109", description: "Ultra-luxury hotel with casino, fine dining, and spectacular shows.", manager: "Sophia Martinez", amenities: ["Casino","Fine Dining","Shows","Spa","Pool Club"] }
];
